"use client";

import {useEffect, useState} from "react";
import {Activity, BarChart3, Boxes, FileCheck2, Landmark, ListChecks, Network, Scale, ShieldAlert, ShieldCheck, Wallet} from "lucide-react";
import {useTranslations, useWallet} from "../providers";
import "./admin.css";

const sections = [["Overview",Activity],["Assets",Boxes],["Pools",Landmark],["Network",Network],["Tier Snapshots",BarChart3],["Nodes",ShieldCheck],["Top100",ListChecks],["Oracles",Scale],["Liquidity",Activity],["Treasuries",Landmark],["Risk",ShieldAlert],["Reconciliation",FileCheck2],["Safe Proposals",ListChecks],["Audit Logs",FileCheck2]] as const;
export default function AdminPage() {
  const t=useTranslations("admin"),{address,connect}=useWallet(); const [selected,setSelected]=useState("Overview"),[auditState,setAuditState]=useState("Sign in with an authorised wallet to load governed data.");
  useEffect(()=>{if(!address)return;void fetch("http://localhost:4000/v1/admin/audit").then(response=>setAuditState(response.status===403?"RBAC access required. Sign in with SIWE through the API.":response.ok?"Audit projection connected.":"API is unavailable.")).catch(()=>setAuditState("API is unavailable."));},[address]);
  return <main className="admin-shell"><aside className="admin-sidebar"><div className="admin-brand"><span>A</span><div><b>ALP</b><small>ADMIN CONSOLE</small></div></div><p>GOVERNED OPERATIONS</p>{sections.map(([name,Icon])=><button key={name} className={selected===name?"selected":""} onClick={()=>setSelected(name)}><Icon size={16}/>{name}</button>)}<div className="admin-testnet"><i/> BSC TESTNET ONLY</div></aside><section className="admin-main"><header><div><p>ADMIN / {selected.toUpperCase()}</p><h1>{selected==="Overview"?t("title"):selected}</h1></div><button className="wallet" onClick={()=>void connect()}>{address?`${address.slice(0,6)}…${address.slice(-4)}`:<><Wallet size={15}/>Connect Admin Wallet</>}</button></header><article className="admin-warning"><ShieldAlert size={18}/><div><b>Safe-first operation</b><span>{t("restricted")}</span></div></article><section className="admin-kpis"><article><span>Deployment</span><strong>Testnet pending</strong><small>Address book is not deployed</small></article><article><span>Role</span><strong>{address?"Verifying":"Disconnected"}</strong><small>SIWE + RBAC required</small></article><article><span>Data source</span><strong>Indexed chain events</strong><small>{auditState}</small></article></section><section className="admin-workspace"><article><p>CONTROL SURFACE</p><h2>{selected}</h2><p>{selected==="Tier Snapshots"?"Generate a deterministic dataset, validate its Merkle root, then prepare a Safe proposal. This interface cannot assign a user tier directly.":"No direct asset movement is available from the web interface. Changes must be prepared, audited and proposed through Safe / timelock controls."}</p><button className="secondary" disabled={!address}>Prepare Safe proposal</button></article><article><p>AUDIT STATUS</p><h2>Chain-derived only</h2><p>{auditState}</p><button className="secondary" disabled={!address}>View audit trail</button></article></section></section></main>;
}
