"use client";

import {useEffect, useState} from "react";
import {ArrowUpRight, ChevronDown, CircleGauge, Globe2, LayoutDashboard, Network, Plus, ShieldCheck, Wallet} from "lucide-react";
import {useLocale, useTranslations, useWallet} from "./providers";
import walletStyles from "./wallet.module.css";

type View = "explore" | "launch" | "portfolio" | "network" | "alp" | "admin";
type DeploymentState = "loading" | "deployed" | "template-not-deployed" | "unavailable";
const views: {id: View; icon: typeof LayoutDashboard}[] = [{id:"explore",icon:LayoutDashboard},{id:"launch",icon:Plus},{id:"portfolio",icon:Wallet},{id:"network",icon:Network},{id:"alp",icon:CircleGauge},{id:"admin",icon:ShieldCheck}];

function WalletButton() {
  const t = useTranslations("common"), {address, connect, disconnect, error} = useWallet();
  return <div className={walletStyles.wrap}>{address ? <button className="wallet" onClick={disconnect}>{address.slice(0,6)}…{address.slice(-4)}<ChevronDown size={14}/></button> : <button className="wallet" onClick={connect}><Wallet size={15}/>{t("connect")}</button>}{error&&<span className={walletStyles.error} role="alert">{error}</span>}</div>;
}
function Metric({label,value,note}:{label:string;value:string;note:string}) { return <article className="metric"><span>{label}</span><strong>{value}</strong><small>{note}</small></article>; }
function Line({label,value,note}:{label:string;value:string;note?:string}) { return <div className="line"><span>{label}</span><b>{value}</b>{note&&<i>{note}</i>}</div>; }
function Heading({eyebrow,title,text}:{eyebrow:string;title:string;text?:string}) { return <section className="page-heading"><p className="eyebrow">{eyebrow}</p><h1>{title}</h1>{text&&<p className="lede">{text}</p>}</section>; }

function AlpApp() {
  const nav=useTranslations("nav"),common=useTranslations("common"),{locale,setLocale}=useLocale(); const [view,setView]=useState<View>("explore"),[open,setOpen]=useState(false),[deployment,setDeployment]=useState<DeploymentState>("loading");
  useEffect(() => { if (window.location.pathname.startsWith("/admin")) setView("admin"); }, []);
  useEffect(()=>{void fetch("/api/protocol").then(response=>response.ok?response.json():Promise.reject()).then(data=>setDeployment(data.status === "deployed" ? "deployed" : "template-not-deployed")).catch(()=>setDeployment("unavailable"));},[]);
  return <main className="app-shell"><div className="mesh mesh-one"/><div className="mesh mesh-two"/><header className="topbar"><button className="brand" onClick={()=>setView("explore")}><span className="brand-glyph">A</span><b>ALP</b><small>ASSET LAUNCH PROTOCOL</small></button><nav>{views.slice(0,5).map(({id})=><button key={id} className={view===id?"active":""} onClick={()=>setView(id)}>{nav(id)}</button>)}</nav><div className="top-actions"><div className="locale"><button className="control" onClick={()=>setOpen(!open)}><Globe2 size={15}/>{locale==="zh-CN"?"中文":"EN"}<ChevronDown size={13}/></button>{open&&<div className="locale-menu"><button onClick={()=>{setLocale("en-US");setOpen(false);}}>English</button><button onClick={()=>{setLocale("zh-CN");setOpen(false);}}>中文</button></div>}</div><span className="network"><i/>{common("testnet")}</span><WalletButton/></div></header><div className="body"><aside><span className="side-label">PROTOCOL</span>{views.map(({id,icon:Icon})=><button key={id} className={view===id?"side active":"side"} onClick={()=>setView(id)}><Icon size={17}/><span>{nav(id)}</span></button>)}<div className="safety"><i/> {common("notReady")}</div></aside><section className="content"><Router view={view} setView={setView} deployment={deployment}/></section></div><nav className="mobile-nav">{views.slice(0,5).map(({id,icon:Icon})=><button key={id} className={view===id?"active":""} onClick={()=>setView(id)}><Icon size={18}/><span>{nav(id)}</span></button>)}</nav></main>;
}
export default function Home() { return <AlpApp/>; }
function Router({view,setView,deployment}:{view:View;setView:(v:View)=>void;deployment:DeploymentState}) { if(view==="launch")return <Launch deployment={deployment}/>;if(view==="portfolio")return <Portfolio/>;if(view==="network")return <NetworkView/>;if(view==="alp")return <Protocol/>;if(view==="admin")return <Admin/>;return <Explore setView={setView} deployment={deployment}/>; }
function Explore({setView,deployment}:{setView:(v:View)=>void;deployment:DeploymentState}) { const t=useTranslations("home"),c=useTranslations("common"), status=deployment==="loading"?c("loading"):deployment==="deployed"?"Chain address book verified":deployment==="template-not-deployed"?"BSC Testnet deployment pending":"Address book unavailable";return <><section className="hero"><div><p className="eyebrow">{t("eyebrow")}</p><h1>{t("title")}</h1><p className="lede">{t("subtitle")}</p><div className="actions"><button className="primary" onClick={()=>setView("explore")}>{t("explore")}<ArrowUpRight size={16}/></button><button className="secondary" disabled={deployment!=="deployed"} onClick={()=>setView("launch")}>{t("launch")}<ArrowUpRight size={16}/></button></div></div><div className="hero-visual"><div className="orbital"><b>ALP</b><small>GLOBAL COMPUTE</small></div><span>RWA</span><span>AI</span><span>IP</span></div></section><section className="metrics"><Metric label={t("assets")} value={deployment==="deployed"?"Loading":"Not indexed"} note={status}/><Metric label={t("liquidity")} value={deployment==="deployed"?"Loading":"Not deployed"} note={status}/><Metric label={t("burned")} value={deployment==="deployed"?"Loading":"Not deployed"} note={status}/><Metric label={t("compute")} value={deployment==="deployed"?"Loading":"Not indexed"} note={status}/></section><section className="section-head"><div><p className="eyebrow">{t("directory")}</p><h2>Connected <em>assets</em></h2></div><div className="chips"><button className="selected">{c("all")}</button><button>RWA</button><button>AI</button><button>Gaming</button><button>IP</button></div></section><section className="cards"><Asset name="CARD" subtitle="Genesis Collectible Asset" status={deployment==="deployed"?c("upcoming"):"TESTNET PENDING"}/></section></>; }
function Asset({name,subtitle,status,action}:{name:string;subtitle:string;status:string;action?:()=>void}) {return <article className={name==="CARD"?"asset featured":"asset"}><div><span className="asset-logo">{name[0]}</span><span className="tag">{status}</span></div><h3>{name}</h3><p>{subtitle}</p><dl><dt>Category</dt><dd>{name==="CARD"?"Collectibles / RWA":"Future vertical"}</dd><dt>Risk state</dt><dd>{name==="CARD"?"Oracle guarded":"Not connected"}</dd></dl><button disabled={!action} onClick={action}>View asset <ArrowUpRight size={14}/></button></article>;}
function Launch({deployment}:{deployment:DeploymentState}){const t=useTranslations("launch"),[raw,setRaw]=useState("1000"),amount=Math.max(0,Number(raw)||0),half=amount/2,q=amount/4,m=(v:number)=>new Intl.NumberFormat("en-US",{maximumFractionDigits:2}).format(v),ready=deployment==="deployed";return <><Heading eyebrow={t("eyebrow")} title={t("title")} text={t("description")}/><div className="two-col"><article className="panel launch-panel"><p className="step">01</p><h3>{t("value")}</h3><label className="amount"><span>USDT</span><input value={raw} onChange={e=>setRaw(e.target.value.replace(/[^\d.]/g,""))}/><b>USD</b></label><Line label={t("partner")} value={`$${m(half)}`} note="50%"/><Line label={t("usdt")} value={`$${m(half)}`} note="50%"/><p className="notice"><ShieldCheck size={16}/>{t("oracle")}</p><WalletButton/></article><article className="panel"><p className="step">02</p><h3>{t("allocation")}</h3><div className="allocation"><div className="donut">50/50</div><div><Line label={t("partner")} value={`$${m(half)}`}/><Line label={t("reward")} value={`$${m(q)}`}/><Line label={t("liquidity")} value={`$${m(q)}`}/></div></div><Line label={t("base")} value={m(amount)}/><Line label={t("time")} value="1% / day"/><Line label={t("effective")} value="—"/><small className="disclaimer">{t("notice")}</small></article></div><section className="confirm panel"><div><p className="eyebrow">CONFIRMATION FLOW</p><h3>Two approvals, one onchain position</h3><small className="disclaimer">{ready?"Contract address book verified. Connect a wallet to continue.":"BSC Testnet contract addresses are not verified yet; approval and submission remain disabled."}</small></div><div className="approval"><button className="secondary" disabled={!ready}>01 {t("approveAsset")}</button><button className="secondary" disabled={!ready}>02 {t("approveUsdt")}</button><button className="primary" disabled={!ready}>03 {t("submit")}</button></div></section></>;}
function Portfolio(){const t=useTranslations("portfolio");return <><Heading eyebrow={t("eyebrow")} title={t("title")}/><section className="portfolio"><article className="panel empty"><Wallet size={25}/><h3>{t("empty")}</h3><WalletButton/></article><div className="stat-list"><Metric label={t("balance")} value="—" note="Wallet balance"/><Metric label={t("positions")} value="—" note="Onchain positions"/><Metric label={t("claimable")} value="—" note="Reward index"/></div></section><article className="panel cycle"><div><p className="eyebrow">{t("cycle")}</p><h3>Connect wallet to load cycle state</h3></div><div className="cycle-track"><i/></div><p>Cycle 1 · 20% requirement · Chain-derived status only</p></article></>}
function NetworkView(){const t=useTranslations("network");return <><Heading eyebrow={t("eyebrow")} title={t("title")}/><div className="two-col"><article className="panel graph"><p className="eyebrow">{t("graph")}</p><div className="nodes"><b>YOU</b><i/><span>—</span><span>—</span><span>—</span></div><small>Three levels load by default. Expand deeper only on request.</small></article><article className="panel"><p className="eyebrow">{t("tierTitle")}</p><h2>— <em>V1–V9</em></h2><div className="progress"><i/></div>{[[t("district"),"—"],[t("next"),"Wallet required"],[t("tier"),"—"]].map(([a,b])=><Line key={a} label={a} value={b}/>)}</article></div><section className="metrics network-metrics">{["direct","depth","active","volume"].map(key=><Metric key={key} label={t(key as "direct")} value="—" note="Onchain graph"/>)}</section></>}
function Protocol(){const t=useTranslations("protocol");return <><Heading eyebrow={t("eyebrow")} title={t("title")}/><section className="metrics protocol-metrics">{[["supply","210,000,000"],["circulating","—"],["burned","—"],["liquidity","—"],["compute","—"],["positions","—"]].map(([k,v])=><Metric key={k} label={t(k as "supply")} value={v} note="Chain-derived"/>)}</section><div className="two-col"><article className="panel flow"><p className="eyebrow">{t("flow")}</p>{[["Position USDT","Reward Treasury"],["Position USDT","Liquidity"],["Pair reserve","Emission + Burn"],["Sell fees","Five protocol treasuries"]].map(([a,b])=><div key={b}><span>{a}</span><i/><b>{b}</b></div>)}</article><article className="panel"><p className="eyebrow">{t("contracts")}</p><Line label="Supply cap" value="210,000,000 ALP"/><Line label="Mint authority" value="None"/><Line label="Main Pair" value="Awaiting testnet deploy"/><Line label="LP lock" value="Awaiting testnet deploy"/></article></div></>}
function Admin(){const t=useTranslations("admin");return <><Heading eyebrow={t("eyebrow")} title={t("title")} text={t("restricted")}/><section className="admin-grid">{[t("assets"),t("pools"),t("risk"),t("treasuries"),t("audit")].map(label=><article className="panel" key={label}><ShieldCheck size={18}/><h3>{label}</h3><p>Safe proposal and chain event view</p><button className="secondary">Open <ArrowUpRight size={14}/></button></article>)}</section></>}
