"use client";

import {useEffect, useState} from "react";
import {ArrowUpRight, ChevronDown, CircleGauge, LayoutDashboard, Network, Plus, ShieldCheck, Wallet} from "lucide-react";
import {useLocale, useTranslations, useWallet} from "./providers";
import walletStyles from "./wallet.module.css";

type View = "explore" | "launch" | "portfolio" | "network" | "alp" | "admin";
type DeploymentState = "loading" | "deployed" | "template-not-deployed" | "unavailable";
const views: {id: View; icon: typeof LayoutDashboard}[] = [{id:"explore",icon:LayoutDashboard},{id:"launch",icon:Plus},{id:"portfolio",icon:Wallet},{id:"network",icon:Network},{id:"alp",icon:CircleGauge},{id:"admin",icon:ShieldCheck}];

function WalletButton() {
  const t = useTranslations("common"), {address, connect, disconnect, error} = useWallet();
  return <div className={walletStyles.wrap}>{address ? <button className="wallet" onClick={disconnect}>{address.slice(0,6)}…{address.slice(-4)}<ChevronDown size={14}/></button> : <button className="wallet" onClick={connect}><Wallet size={15}/>{t("connect")}</button>}{error&&<span className={walletStyles.error} role="alert">{error}</span>}</div>;
}
function Metric({label,value,note}:{label:string;value:string;note:string}) { return <article className="metric"><span>{label}</span><strong>{value}</strong><small>{note}</small></article>; }
function Line({label,value,note}:{label:string;value:string;note?:string}) { return <div className="line"><span>{label}</span><b>{value}</b>{note&&<i>{note}</i>}</div>; }
function Heading({eyebrow,title,text}:{eyebrow:string;title:string;text?:string}) { return <section className="page-heading"><p className="eyebrow">{eyebrow}</p><h1>{title}</h1>{text&&<p className="lede">{text}</p>}</section>; }
function LocaleSwitcher() {
  const common=useTranslations("common"),{locale,setLocale}=useLocale(); const [open,setOpen]=useState(false);
  const choose=(next:"en-US"|"zh-CN")=>{setLocale(next);setOpen(false);};
  return <div className="locale"><button className="locale-trigger" type="button" aria-label={common("language")} aria-expanded={open} aria-controls="locale-menu" onClick={()=>setOpen(!open)}><span className="locale-icon" aria-hidden="true">🌐</span><span className="locale-label">{locale==="zh-CN"?"中文":"EN"}</span><ChevronDown className="locale-chevron" size={13}/></button>{open&&<><button className="locale-backdrop" type="button" aria-label={common("cancel")} onClick={()=>setOpen(false)}/><div className="locale-menu" id="locale-menu" role="menu" aria-label={common("language")}><p>{common("language")}</p><button type="button" role="menuitemradio" aria-checked={locale==="en-US"} className={locale==="en-US"?"active":""} onClick={()=>choose("en-US")}><span>English</span>{locale==="en-US"&&<span aria-hidden="true">✓</span>}</button><button type="button" role="menuitemradio" aria-checked={locale==="zh-CN"} className={locale==="zh-CN"?"active":""} onClick={()=>choose("zh-CN")}><span>简体中文</span>{locale==="zh-CN"&&<span aria-hidden="true">✓</span>}</button><button className="locale-cancel" type="button" onClick={()=>setOpen(false)}>{common("cancel")}</button></div></>}</div>;
}

function AlpApp() {
  const nav=useTranslations("nav"),common=useTranslations("common"); const [view,setView]=useState<View>("explore"),[deployment,setDeployment]=useState<DeploymentState>("loading");
  useEffect(() => { if (window.location.pathname.startsWith("/admin")) setView("admin"); }, []);
  useEffect(()=>{void fetch("/api/protocol").then(response=>response.ok?response.json():Promise.reject()).then(data=>setDeployment(data.status === "deployed" ? "deployed" : "template-not-deployed")).catch(()=>setDeployment("unavailable"));},[]);
  return <main className="app-shell"><div className="mesh mesh-one"/><div className="mesh mesh-two"/><header className="topbar"><button className="brand" onClick={()=>setView("explore")}><span className="brand-glyph">A</span><b>ALP</b><small>ASSET LAUNCH PROTOCOL</small></button><nav>{views.slice(0,5).map(({id})=><button key={id} className={view===id?"active":""} onClick={()=>setView(id)}>{nav(id)}</button>)}</nav><div className="top-actions"><LocaleSwitcher/><span className="network"><i/>{common("testnet")}</span><WalletButton/></div></header><div className="body"><aside><span className="side-label">PROTOCOL</span>{views.map(({id,icon:Icon})=><button key={id} className={view===id?"side active":"side"} onClick={()=>setView(id)}><Icon size={17}/><span>{nav(id)}</span></button>)}<div className="safety"><i/> {common("notReady")}</div></aside><section className="content"><Router view={view} setView={setView} deployment={deployment}/></section></div><nav className="mobile-nav">{views.slice(0,5).map(({id,icon:Icon})=><button key={id} className={view===id?"active":""} onClick={()=>setView(id)}><Icon size={18}/><span>{nav(id)}</span></button>)}</nav></main>;
}
export default function Home() { return <AlpApp/>; }
function Router({view,setView,deployment}:{view:View;setView:(v:View)=>void;deployment:DeploymentState}) { if(view==="launch")return <Launch deployment={deployment}/>;if(view==="portfolio")return <Portfolio/>;if(view==="network")return <NetworkView/>;if(view==="alp")return <Protocol/>;if(view==="admin")return <Admin/>;return <Explore setView={setView} deployment={deployment}/>; }
function Explore({setView,deployment}:{setView:(v:View)=>void;deployment:DeploymentState}) { const t=useTranslations("home"),c=useTranslations("common"), status=deployment==="loading"?c("loading"):deployment==="deployed"?c("addressBookVerified"):deployment==="template-not-deployed"?c("testnetPending"):c("addressBookUnavailable");return <><section className="hero"><div><p className="eyebrow">{t("eyebrow")}</p><h1>{t("title")}</h1><p className="lede">{t("subtitle")}</p><div className="actions"><button className="primary" onClick={()=>setView("explore")}>{t("explore")}<ArrowUpRight size={16}/></button><button className="secondary" disabled={deployment!=="deployed"} onClick={()=>setView("launch")}>{t("launch")}<ArrowUpRight size={16}/></button></div></div><div className="hero-visual"><div className="orbital"><b>ALP</b><small>GLOBAL COMPUTE</small></div><span>RWA</span><span>AI</span><span>IP</span></div></section><section className="metrics"><Metric label={t("assets")} value={deployment==="deployed"?c("loading"):c("notIndexed")} note={status}/><Metric label={t("liquidity")} value={deployment==="deployed"?c("loading"):c("notDeployed")} note={status}/><Metric label={t("burned")} value={deployment==="deployed"?c("loading"):c("notDeployed")} note={status}/><Metric label={t("compute")} value={deployment==="deployed"?c("loading"):c("notIndexed")} note={status}/></section><section className="section-head"><div><p className="eyebrow">{t("directory")}</p><h2>{c("connectedAssets")}</h2></div><div className="chips"><button className="selected">{c("all")}</button><button>RWA</button><button>AI</button><button>Gaming</button><button>IP</button></div></section><section className="cards"><Asset name={c("relique")} token="CARD" subtitle={c("reliqueSubtitle")} status={deployment==="deployed"?c("upcoming"):c("testnetPending")}/></section></>; }
function Asset({name,token,subtitle,status,action}:{name:string;token:string;subtitle:string;status:string;action?:()=>void}) {const c=useTranslations("common");return <article className="asset featured"><div><span className="asset-logo">{name[0]}</span><span className="tag">{status}</span></div><h3>{name}</h3><p>{subtitle}</p><dl><dt>{c("token")}</dt><dd>{token}</dd><dt>{c("category")}</dt><dd>{c("collectiblesRwa")}</dd><dt>{c("riskState")}</dt><dd>{c("oracleGuarded")}</dd></dl><button disabled={!action} onClick={action}>{c("view")} <ArrowUpRight size={14}/></button></article>;}
function Launch({deployment}:{deployment:DeploymentState}){const t=useTranslations("launch"),c=useTranslations("common"),[raw,setRaw]=useState("1000"),[quote,setQuote]=useState<{partnerAmount:string;usdtAmount:string;priceE18:string}|null>(null),[quoteError,setQuoteError]=useState<string>(),amount=Math.max(0,Number(raw)||0),ready=deployment==="deployed",m=(v:number)=>new Intl.NumberFormat("en-US",{maximumFractionDigits:2}).format(v),format=(value?:string)=>value?m(Number(BigInt(value)/10n**16n)/100):"—";useEffect(()=>{if(!ready||!amount){setQuote(null);return;}const timer=setTimeout(()=>void fetch(`/api/quote?totalValue=${BigInt(Math.round(amount*100))*10n**16n}`).then(async response=>{const body=await response.json() as {partnerAmount?:string;usdtAmount?:string;priceE18?:string;error?:string};if(!response.ok)throw new Error(body.error);setQuote({partnerAmount:body.partnerAmount!,usdtAmount:body.usdtAmount!,priceE18:body.priceE18!});setQuoteError(undefined);}).catch(error=>{setQuote(null);setQuoteError(error instanceof Error?error.message:"Quote unavailable");}),250);return()=>clearTimeout(timer);},[amount,ready]);return <><Heading eyebrow={t("eyebrow")} title={t("title")} text={t("description")}/><div className="two-col"><article className="panel launch-panel"><p className="step">01</p><h3>{t("value")}</h3><label className="amount"><span>USDT</span><input value={raw} onChange={e=>setRaw(e.target.value.replace(/[^\d.]/g,""))}/><b>USD</b></label><Line label={t("partner")} value={format(quote?.partnerAmount)} note={ready?c("onchainQuote"):c("pendingDeployment")}/><Line label={t("usdt")} value={format(quote?.usdtAmount)} note={ready?c("onchainQuote"):c("pendingDeployment")}/><p className="notice"><ShieldCheck size={16}/>{quoteError??t("oracle")}</p><WalletButton/></article><article className="panel"><p className="step">02</p><h3>{t("allocation")}</h3><div className="allocation"><div className="donut">{ready?"QUOTE":"—"}</div><div><Line label={t("partner")} value={format(quote?.partnerAmount)}/><Line label={t("reward")} value={quote?format((BigInt(quote.usdtAmount)/2n).toString()):"—"}/><Line label={t("liquidity")} value={quote?format((BigInt(quote.usdtAmount)/2n).toString()):"—"}/></div></div><Line label={t("base")} value={m(amount)}/><Line label={t("time")} value="1% / day"/><Line label={t("effective")} value="—"/><small className="disclaimer">{t("notice")}</small></article></div><section className="confirm panel"><div><p className="eyebrow">{c("confirmationFlow")}</p><h3>{c("twoApprovals")}</h3><small className="disclaimer">{ready?c("addressBookReady"):c("addressBookPending")}</small></div><div className="approval"><button className="secondary" disabled={!ready||!quote}>01 {t("approveAsset")}</button><button className="secondary" disabled={!ready||!quote}>02 {t("approveUsdt")}</button><button className="primary" disabled={!ready||!quote}>03 {t("submit")}</button></div></section></>;}
function Portfolio(){const t=useTranslations("portfolio"),c=useTranslations("common");return <><Heading eyebrow={t("eyebrow")} title={t("title")}/><section className="portfolio"><article className="panel empty"><Wallet size={25}/><h3>{t("empty")}</h3><WalletButton/></article><div className="stat-list"><Metric label={t("balance")} value="—" note={c("walletBalance")}/><Metric label={t("positions")} value="—" note={c("onchainPositions")}/><Metric label={t("claimable")} value="—" note={c("rewardIndex")}/></div></section><article className="panel cycle"><div><p className="eyebrow">{t("cycle")}</p><h3>{c("connectToLoadCycle")}</h3></div><div className="cycle-track"><i/></div><p>{c("cycleStatus")}</p></article></>}
function NetworkView(){const t=useTranslations("network");return <><Heading eyebrow={t("eyebrow")} title={t("title")}/><div className="two-col"><article className="panel graph"><p className="eyebrow">{t("graph")}</p><div className="nodes"><b>YOU</b><i/><span>—</span><span>—</span><span>—</span></div><small>Three levels load by default. Expand deeper only on request.</small></article><article className="panel"><p className="eyebrow">{t("tierTitle")}</p><h2>— <em>V1–V9</em></h2><div className="progress"><i/></div>{[[t("district"),"—"],[t("next"),"Wallet required"],[t("tier"),"—"]].map(([a,b])=><Line key={a} label={a} value={b}/>)}</article></div><section className="metrics network-metrics">{["direct","depth","active","volume"].map(key=><Metric key={key} label={t(key as "direct")} value="—" note="Onchain graph"/>)}</section></>}
function Protocol(){const t=useTranslations("protocol"),c=useTranslations("common");return <><Heading eyebrow={t("eyebrow")} title={t("title")}/><section className="metrics protocol-metrics">{[["supply","210,000,000"],["circulating","—"],["burned","—"],["liquidity","—"],["compute","—"],["positions","—"]].map(([k,v])=><Metric key={k} label={t(k as "supply")} value={v} note={c("chainDerived")}/>)}</section><div className="two-col"><article className="panel flow"><p className="eyebrow">{t("flow")}</p>{[["Position USDT","Reward Treasury"],["Position USDT","Liquidity"],["Pair reserve","Emission + Burn"],["Sell fees","Five protocol treasuries"]].map(([a,b])=><div key={b}><span>{a}</span><i/><b>{b}</b></div>)}</article><article className="panel"><p className="eyebrow">{t("contracts")}</p><Line label="Supply cap" value="210,000,000 ALP"/><Line label="Mint authority" value="None"/><Line label={c("mainPair")} value={c("awaitingTestnetDeploy")}/><Line label={c("lpLock")} value={c("awaitingTestnetDeploy")}/></article></div></>}
function Admin(){const t=useTranslations("admin");return <><Heading eyebrow={t("eyebrow")} title={t("title")} text={t("restricted")}/><section className="admin-grid">{[t("assets"),t("pools"),t("risk"),t("treasuries"),t("audit")].map(label=><article className="panel" key={label}><ShieldCheck size={18}/><h3>{label}</h3><p>Safe proposal and chain event view</p><button className="secondary">Open <ArrowUpRight size={14}/></button></article>)}</section></>}
