"use client";

import Link from "next/link";
import {AppShell, WalletButton} from "../components/app-shell";
import {EmptyState, Metric, ProductHeader, StatusBadge} from "../components/ui";
import {useTranslations, useWallet} from "../providers";

const pending=<StatusBadge state="TESTNET_PENDING"/>;
export function ExplorePage(){const t=useTranslations("common");return <AppShell title="Explore"><section className="explore-hero"><div><p>ASSET LAUNCH PROTOCOL</p><h1>The infrastructure for launching global assets onchain.</h1><span>Connect assets. Activate liquidity. Build global markets.</span><div><Link className="primary" href="/app/assets/relique">Explore Assets</Link><Link className="secondary" href="/app/launch/relique">Launch RELIQUE</Link></div></div><AssetNetwork/></section><section className="product-metrics">{["Total Assets Connected","Protocol Liquidity","ALP Burned","Global Compute"].map((label,index)=><Metric key={label} label={label} state={index===0||index===3?"INDEXER_PENDING":"TESTNET_PENDING"}/>)}</section><section className="product-section"><header><p>ASSET DIRECTORY</p><h2>{t("connectedAssets")}</h2></header><Link href="/app/assets/relique" className="asset-card"><b>RELIQUE</b><span>Genesis Collectibles / RWA Asset</span><small>Token: CARD · Collectibles / RWA</small>{pending}</Link></section></AppShell>}
function AssetNetwork(){return <div className="asset-network"><b>ALP</b>{["RELIQUE","RWA","AI","Gaming","IP"].map(label=><span key={label} className={label==="RELIQUE"?"genesis":""}>{label}</span>)}</div>}
export function LaunchPage(){return <AppShell title="Launch"><ProductHeader eyebrow="ASSET LAUNCH" title="Participate in the RELIQUE launch" subtitle="Token: CARD · Collectibles / RWA"/><div className="product-grid"><section className="panel"><h3>Your Participation</h3><label>Total Participation Value<input value="" placeholder="0.00" readOnly/></label><p>50% RELIQUE / CARD Value</p><p>50% USDT</p><p>Oracle Price —</p>{pending}</section><section className="panel"><h3>Protocol Allocation</h3><div className="allocation-list"><b>50% <span>Partner Asset Vault</span></b><b>25% <span>Reward Treasury</span></b><b>25% <span>ALP Liquidity</span></b></div><p>Time Compute Compensation</p><small>+1% compute factor per launch day. This is a compute-weight adjustment, not a daily financial return.</small></section></div><section className="panel transaction-pending"><b>TESTNET CONTRACTS PENDING</b><p>Contract addresses are not verified yet. Transactions remain disabled.</p><button disabled>Approve CARD</button><button disabled>Approve USDT</button><button disabled>Create Position</button></section></AppShell>}
export function PortfolioPage(){const {address,state}=useWallet();return <AppShell title="Portfolio"><ProductHeader eyebrow="PORTFOLIO" title="Portfolio" subtitle="Positions, compute and rewards — accounted onchain."/>{state!=="connected"?<EmptyState title="Connect wallet to view your portfolio." detail="Connect a supported BSC Testnet wallet to load onchain positions." action={<WalletButton/>}/>:<><section className="product-metrics">{["ALP Balance","Active Positions","Effective Compute","Claimable ALP","Network Rewards"].map(label=><Metric key={label} label={label} state="EMPTY"/>)}</section><EmptyState title="No active positions yet." detail={`Your wallet ${address?.slice(0,6)}…${address?.slice(-4)} is connected. Join an asset launch to create your first position.`} action={<Link className="primary" href="/app/launch/relique">Launch RELIQUE</Link>}/></>}</AppShell>}
export function NetworkPage(){const {state}=useWallet();return <AppShell title="Network"><ProductHeader eyebrow="ALP NETWORK" title="ALP Network" subtitle="Unlimited-depth network performance with verifiable onchain rewards."/><section className="network-rules"><span>Performance depth: <b>Unlimited</b></span><span>Referral rewards: <b>Up to 20 levels</b></span><span>Differential distribution: <b>Up to 20 levels</b></span></section>{state==="connected"?<EmptyState title="No network activity yet." detail="Network graph and tier progress appear only when indexed onchain data exists."/>:<EmptyState title="Connect wallet to view your network." detail="No network graph or tier progress is shown without verified wallet data."/>}</AppShell>}
export function ProtocolPage(){return <AppShell title="Protocol"><ProductHeader eyebrow="PROTOCOL TRANSPARENCY" title="ALP Protocol" subtitle="Supply, liquidity, emissions and contract state — publicly verifiable."/><section className="product-metrics">{["Total Supply","Circulating Supply","Total Burned","Genesis Reserve","Pair ALP Reserve","Pair USDT Reserve","Protocol Liquidity","Global Compute","Current Epoch","Emission Rate","Burn Rate","Sell Fee","LP Lock Status"].map(label=><Metric key={label} label={label} state="TESTNET_PENDING"/>)}</section><section className="product-grid"><section className="panel"><h3>Token Flow</h3><p>Partner Asset → Partner Asset Vault</p><p>USDT → 50% Reward Treasury · 50% ALP Liquidity</p><p>ALP Pair Reserve → Burn · Emission → Global Compute</p><p>ALP Sell → 17% protocol allocation</p></section><section className="panel"><h3>Contract Addresses</h3><p>Testnet deployment pending.</p>{["ALP Token","Main Pair","Genesis Reserve","Liquidity Manager","Emission Engine","Oracle Router","RELIQUE Pool","CARD Token"].map(label=><p key={label}>{label} <span>—</span></p>)}</section></section></AppShell>}
export function SimplePage({title}:{title:string}){return <AppShell title={title}><ProductHeader eyebrow="ALP" title={title} subtitle="Onchain data will appear after verified testnet deployment and indexing."/><EmptyState title="Testnet data pending." detail="This section intentionally has no fabricated metrics or rankings."/></AppShell>}
